Repository umc-bonheur/bonheur-server, pull requests merged in 2023-01, with the labels that each got.

#25 [Fix] Entity 수정
  src/main/java/com/bonheur/domain/image/model/Image.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/member/model/MemberProfile.java
Labels: 수정

#32 [Feat] 소셜 회원가입 기능 추가
  src/main/java/com/bonheur/config/client/apple/AppleTokenDecoder.java
  src/main/java/com/bonheur/config/client/apple/dto/AppleTokenPayload.java
  src/main/java/com/bonheur/config/client/kakao/KakaoAuthApiClient.java
  src/main/java/com/bonheur/config/client/kakao/dto/KakaoAccount.java
  src/main/java/com/bonheur/config/client/kakao/dto/KakaoProfileResponse.java
  src/main/java/com/bonheur/config/provider/AppleAuthProvider.java
  src/main/java/com/bonheur/config/provider/AuthProvider.java
  src/main/java/com/bonheur/config/provider/KakaoAuthProvider.java
  src/main/java/com/bonheur/domain/auth/controller/AuthController.java
  src/main/java/com/bonheur/domain/auth/model/dto/SocialSignUpRequest.java
  src/main/java/com/bonheur/domain/auth/model/dto/SocialSignUpResponse.java
  src/main/java/com/bonheur/domain/auth/service/AuthProviderFinder.java
  src/main/java/com/bonheur/domain/auth/service/AuthProviderFinderImpl.java
  src/main/java/com/bonheur/domain/auth/service/AuthService.java
  src/main/java/com/bonheur/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/bonheur/domain/common/dto/ApiResponse.java
  src/main/java/com/bonheur/domain/common/exception/BonheurBaseException.java
  src/main/java/com/bonheur/domain/common/exception/InvalidException.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/member/model/dto/CreateMemberRequest.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: 서비스 개발

#40 [CHORE] 스웨거 설정 추가
  build.gradle
  src/main/java/com/bonheur/config/swagger/SpringDocsConfig.java
  src/main/java/com/bonheur/config/swagger/dto/ApiDocumentResponse.java
  src/main/java/com/bonheur/domain/auth/controller/AuthController.java
  src/main/java/com/bonheur/domain/image/model/Image.java
  src/main/resources/application.yml
Labels: dependencies, 세팅

#50 [Feat] 회원 인증 로직 추가
  build.gradle
  src/main/java/com/bonheur/config/client/kakao/KakaoAuthApiClient.java
  src/main/java/com/bonheur/config/interceptor/Auth.java
  src/main/java/com/bonheur/config/interceptor/AuthInterceptor.java
  src/main/java/com/bonheur/config/interceptor/LoginCheckHandler.java
  src/main/java/com/bonheur/config/provider/KakaoAuthProvider.java
  src/main/java/com/bonheur/config/resolver/MemberId.java
  src/main/java/com/bonheur/config/resolver/MemberIdResolver.java
  src/main/java/com/bonheur/config/session/SessionConfig.java
  src/main/java/com/bonheur/config/web/WebConfig.java
  src/main/java/com/bonheur/config/webclient/WebClientConfig.java
  src/main/java/com/bonheur/domain/common/exception/InternalServerException.java
  src/main/java/com/bonheur/domain/common/exception/InvalidException.java
  src/main/java/com/bonheur/domain/common/exception/UnAuthorizedException.java
Labels: 서비스 개발, 테스크

#59 [Feat] Board 작성 기능, 수정 기능 추가
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/Board.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/model/BoardTag.java
  src/main/java/com/bonheur/domain/boardtag/repository/BoardTagRepository.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/image/model/Image.java
  src/main/java/com/bonheur/domain/image/repository/ImageRepository.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepository.java
  src/main/java/com/bonheur/domain/tag/model/Tag.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepository.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 서비스 개발

#79 [Feat] 마이 프로필 수정 기능 추가
  build.gradle
  src/main/java/com/bonheur/config/interceptor/AuthInterceptor.java
  src/main/java/com/bonheur/config/interceptor/LoginCheckHandler.java
  src/main/java/com/bonheur/config/redis/RedisConfig.java
  src/main/java/com/bonheur/config/resolver/MemberIdResolver.java
  src/main/java/com/bonheur/config/session/SessionConfig.java
  src/main/java/com/bonheur/config/session/SessionConstant.java
  src/main/java/com/bonheur/domain/auth/controller/AuthController.java
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/Board.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/model/BoardTag.java
  src/main/java/com/bonheur/domain/boardtag/repository/BoardTagRepository.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/image/model/Image.java
  src/main/java/com/bonheur/domain/image/repository/ImageRepository.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileResponse.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepository.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/model/Tag.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepository.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
  src/main/resources/application.yml
Labels: 서비스 개발

#82 [Feat] 마이 프로필 수정 기능 추가
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileResponse.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 서비스 개발

#88 [Feat] 회원 탈퇴 API 추가
  src/main/java/com/bonheur/domain/auth/controller/AuthController.java
  src/main/java/com/bonheur/domain/auth/service/AuthService.java
  src/main/java/com/bonheur/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/tag/model/Tag.java
Labels: 서비스 개발, 세팅

#94 [fix] Validation 방식 변경
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagRequest.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 수정

#92 [Feat] 마이페이지 통계(종합/월별/요일별/시간별/태그별) API 추가
  src/main/java/com/bonheur/domain/board/repository/BoardRepository.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/FindActiveRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindDayRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindMonthRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindTagRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindTimeRecordResponse.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 서비스 개발

#99 [Fix] 행복 기록 작성 및 수정 기능 로직 수정 피드백 반영
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepository.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/FindActiveRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindDayRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindMonthRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindTagRecordResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/FindTimeRecordResponse.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagRequest.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagResponse.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 수정

#81 [Feat] 게시글 전체 조회, 게시글 해시태그로 조회, 게시글 삭제 API 구현
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/DeleteBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardByTagRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
Labels: 서비스 개발

#103 [Feat] 회원 최근 사용 태그 조회
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/GetTagUsedByMemberResponse.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 서비스 개발

#107 [Refactor] 행복 기록 작성 및 수정 기능 관련 코드
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/DeleteBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardByTagRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/repository/BoardTagRepository.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/image/repository/ImageRepository.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/GetTagUsedByMemberResponse.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/membertag/repository/MemberTagRepository.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagService.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagServiceImpl.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepository.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 수정

#95 [Fix] 행복 기록 작성 및 수정 기능 로직 수정
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/repository/BoardTagRepository.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/image/repository/ImageRepository.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/membertag/repository/MemberTagRepository.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagService.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagServiceImpl.java
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagRequest.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagResponse.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 수정

#108 [Feat] 프로필 조회 기능 추가
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/repository/BoardTagRepository.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/image/repository/ImageRepository.java
  src/main/java/com/bonheur/domain/image/service/ImageService.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/GetMemberProfileResponse.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/membertag/repository/MemberTagRepository.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagService.java
  src/main/java/com/bonheur/domain/membertag/service/MemberTagServiceImpl.java
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagRequest.java
  src/main/java/com/bonheur/domain/tag/model/dto/CreateTagResponse.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 서비스 개발

#109 [Feat] 프로필 조회 기능 추가
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/dto/GetMemberProfileResponse.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 서비스 개발

#106 [Fix] 'Board' 전체 조회 및 태그로 조회 날짜별로 그룹화
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsGroupsResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
Labels: 수정
