Repository umc-bonheur/bonheur-server, pull requests merged in 2023-02, with the labels that each got.

#127 [Feat] 공통 에러 처리
  src/main/java/com/bonheur/config/advice/ControllerExceptionAdvice.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceHelper.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
  src/main/resources/application.yml
Labels: 테스크

#130 [DEPLOY] Github Actions, CodeDeploy, S3를 사용한 자동 배포
  .github/workflows/github-actions.yml
  .gitignore
  appspec.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/com/bonheur/config/redis/RedisConfig.java
  src/main/resources/application.yml
Labels: 운영 배포

#131 hotfix: github actions gradlew 권한 추가
  .github/workflows/github-actions.yml
Labels: 운영 배포

#135 Feature/member annotation #129
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
Labels: 개선 작업

#139 [Fix] 게시물 상세조회 API 수정
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
Labels: 수정

#143 [Feat] 예외 클래스 생성
  src/main/java/com/bonheur/domain/common/exception/ConflictException.java
  src/main/java/com/bonheur/domain/common/exception/ForbiddenException.java
  src/main/java/com/bonheur/domain/common/exception/NotFoundException.java
  src/main/java/com/bonheur/domain/common/exception/NotImplementedException.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 개선 작업, 수정

#149 feat: 커스텀 예외 핸들러 추가
  src/main/java/com/bonheur/config/advice/ControllerExceptionAdvice.java
Labels: 개선 작업

#152 [Feat] 예외처리 추가
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/util/FileUploadUtil.java
  src/main/java/com/bonheur/util/FileUploadUtilHelper.java
Labels: 개선 작업

#156 fix : 에러 처리 함수 public 선언
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/util/FileUploadUtilHelper.java
Labels: 수정

#157 fix : 에러 처리 함수 public 선언
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/util/FileUploadUtilHelper.java
Labels: 수정

#147 [Fix] orderType 파라미터 추가로 "게시글 조회" 정렬순 선택
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsGroupsResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/util/OrderSpecifierUtil.java
Labels: 수정

#162 [Fix] Redis Session 유효시간 변경
  src/main/java/com/bonheur/config/redis/RedisConfig.java
Labels: 수정

#167 [Feat] 게시글, 프로필, 태그 관련 예외처리 추가
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceHelper.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustom.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
  src/main/java/com/bonheur/util/FileUploadUtilHelper.java
Labels: 서비스 개발

#172 fix : validateImageCount 함수 로직 변경
  src/main/java/com/bonheur/domain/image/service/ImageServiceHelper.java
Labels: 수정

#170 [Feat] dto validation 어노테이션 추가
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardByTagRequest.java
Labels: 개선 작업

#177 fix : ErrorCode 관련 피드백 적용
  src/main/java/com/bonheur/config/redis/RedisConfig.java
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardByTagRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsGroupsResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/common/exception/UnAuthorizedException.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
  src/main/java/com/bonheur/util/OrderSpecifierUtil.java
Labels: 수정

#181 fix : 프로필 수정에서 List<MultipartFile> image을 MultipartFile 타입으로 변경
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#168 [Feat] 게시글, 프로필, 태그 관련 예외처리 추가
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagService.java
  src/main/java/com/bonheur/domain/boardtag/service/BoardTagServiceImpl.java
  src/main/java/com/bonheur/domain/common/exception/UnAuthorizedException.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceHelper.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepository.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceHelper.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustom.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 개선 작업

#174 [Fix] 회원가입 API 수정
  src/main/java/com/bonheur/domain/auth/controller/AuthController.java
  src/main/java/com/bonheur/domain/auth/service/AuthService.java
  src/main/java/com/bonheur/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/bonheur/domain/member/model/Member.java
  src/main/java/com/bonheur/domain/member/model/dto/CreateMemberRequest.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#186 feat : 게시글 글자수 초과 validation 추가
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileResponse.java
Labels: 개선 작업

#190 hotfix : findOwnTagByTagId 함수 수정
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileResponse.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustomImpl.java
Labels: 핫픽스

#187 feat : 게시글 작성 및 수정 DTO 글자수 validation 추가
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/CreateBoardResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/UpdateBoardResponse.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileResponse.java
Labels: 개선 작업

#185 [Feat] 게시글 전체 조회, 게시글 태그별 조회 예외 처리
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardByTagRequest.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsGroupsResponse.java
  src/main/java/com/bonheur/domain/board/model/dto/GetBoardsRequest.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bonheur/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustom.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
Labels: 서비스 개발

#201 [Fix] 프로필 기본 이미지 조회 로직 및 RequestPart 어노테이션 수정
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/service/BoardService.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceHelper.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/common/exception/dto/ErrorCode.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceHelper.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
  src/main/java/com/bonheur/util/DateUtilHelper.java
Labels: 수정

#207 fix : MemberProperties 클래스 선언
  src/main/java/com/bonheur/domain/member/model/property/MemberProperties.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#205 [Feat] 닉네임 Validation 추가
  src/main/java/com/bonheur/config/advice/ControllerExceptionAdvice.java
  src/main/java/com/bonheur/config/validator/NickName.java
  src/main/java/com/bonheur/config/validator/NickNameValidator.java
  src/main/java/com/bonheur/domain/auth/model/dto/SocialSignUpRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/CreateMemberRequest.java
Labels: 수정, 세팅

#202 [Fix] 프로필 기본 이미지 조회 로직 및 RequestPart 어노테이션 수정
  src/main/java/com/bonheur/domain/board/controller/BoardController.java
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
  src/main/java/com/bonheur/domain/image/service/ImageServiceImpl.java
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/model/property/MemberProperties.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#212 [feat] 프로필 수정 닉네임 validation 추가
  src/main/java/com/bonheur/config/validator/NickNameValidator.java
  src/main/java/com/bonheur/domain/auth/model/dto/SocialSignUpRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/CreateMemberRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileRequest.java
Labels: 수정

#213 [feat] 프로필 수정 닉네임 validation 추가
  src/main/java/com/bonheur/config/validator/NickNameValidator.java
  src/main/java/com/bonheur/domain/auth/model/dto/SocialSignUpRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/CreateMemberRequest.java
  src/main/java/com/bonheur/domain/member/model/dto/UpdateMemberProfileRequest.java
Labels: 수정

#216 [Fix] 통계 API Response 값 수정
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#218 Fix : tagName으로 tagId 조회 uri 수정
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
Labels: 수정

#219 [Fix] 통계 api (요일/월) 오류 수정
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
Labels: 수정

#221 Fix : 최근 tag 조회 도메인 변경(member -> tag)
  src/main/java/com/bonheur/domain/member/controller/MemberController.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberService.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
  src/main/java/com/bonheur/domain/tag/controller/TagController.java
  src/main/java/com/bonheur/domain/tag/model/dto/GetTagUsedByMemberResponse.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustom.java
  src/main/java/com/bonheur/domain/tag/repository/TagRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/tag/service/TagService.java
  src/main/java/com/bonheur/domain/tag/service/TagServiceImpl.java
Labels: 수정

#223 [Fix] 통계 api 월/일 포맷 수정
  src/main/java/com/bonheur/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/bonheur/domain/member/service/MemberServiceImpl.java
Labels: 수정

#226 Fix : 날짜 형식 변경
  src/main/java/com/bonheur/domain/board/service/BoardServiceImpl.java
Labels: 수정
